config/routes.rb
Rails.application.routes.draw do
	root to: "variations#index"

  get 'users', to: 'users#create', as: :create_user
  post 'logout', to: 'users#logout'

  resources :users, only: [:new, :update, :edit, :destroy]
  resources :variations, only: [:create, :new, :edit, :update, :destroy]

  get '/privacy-policy', to: "pages#privacy_policy", as: :privacy_policy
  get '/terms-and-conditions', to: "pages#terms_and_conditions", as: :terms_and_conditions

  get '/:range', to: "variations#index", as: :variations_range
end

app/models/variation.rb
class Variation < ApplicationRecord
  belongs_to :user, touch: true

  validates :value, presence: true
  validates :label, presence: true

  scope :from_today, -> (date) {
    where(%{
      (
        (? < variations.created_at + variations.spread * interval '1 day' AND ? > variations.created_at) OR
        (
          variations.recurring = ? AND (
              variations.spread = 1 OR
              ? < date_trunc('MONTH', variations.created_at)::DATE + variations.spread * interval '1 month'
            )
        )
      ) AND variations.base = ?
    }, date.end_of_day, date.end_of_day, true, date.beginning_of_month, false)
  }
  scope :from_this_month, -> (date) {
    where(%{
      variations.created_at > ? OR
      (
        variations.recurring = ? AND (
          variations.spread = 1 OR
          ? < date_trunc('MONTH', variations.created_at)::DATE + variations.spread * interval '1 month'
        )
      )
    }, date.beginning_of_month, true, date.beginning_of_month)
  }

  def daily_value(date)
    if self.recurring?
      value / date.end_of_month.day
    else
      value.to_f / spread
    end
  end

  def monthly_value
    value
  end

  def monthly_value_up_to_date(date)
    current_spread = date.day - created_at.day + 1
    if current_spread > spread
      value
    else
      daily_value(date) * current_spread
    end
  end
end

app/controllers/variations_controller.rb
class VariationsController < ApplicationController
  before_action :redirect_to_default_range, only: [:index]

  def index
    @date = params[:date] ? Time.zone.parse(params[:date]) : Time.zone.now
    @variations =
      if params[:range] == 'this-month'
        @current_user.variations.from_this_month(@date)
      else
        @current_user.variations.from_today(@date)
      end
  end

  def new
  end

  def create
    variation = Variation.new(params.require(:variation).permit(:value, :user_id, :base, :recurring, :label, :spread))
    authorize variation

    if variation.save
      redirect_to(variation.recurring || variation.base ? variations_range_url(range: 'this-month') : variations_range_url(range: 'today'))
    else
      redirect_back fallback_location: root_url, flash: { error: "An unexpected error occured."}
    end
  end

  def edit
    @variation = Variation.find(params[:id])
    authorize @variation
  end

  def update
    variation = Variation.find(params[:id])
    variation.assign_attributes(params.require(:variation).permit(:value, :user_id, :base, :recurring, :label, :spread))
    authorize variation

    if variation.save
      redirect_to(variation.recurring || variation.base ? variations_range_url(range: 'this-month') : variations_range_url(range: 'today'))
    else
      redirect_back fallback_location: root_url, flash: { error: "An unexpected error occured."}
    end
  end

  def destroy
    variation = Variation.find(params[:id])
    authorize variation
    variation.destroy

    redirect_to(variation.recurring || variation.base ? variations_range_url(range: 'this-month') : variations_range_url(range: 'today'))
  end

  protected

  def redirect_to_default_range
    redirect_to variations_range_url(range: "today") if params[:range].blank?
  end
end

app/helpers/variations_helper.rb
module VariationsHelper
  def current_monthly_budget
    @current_monthly_budget ||= @current_user.monthly_budget - @variations.map(&:monthly_value).sum
  end

  def current_daily_budget
    @current_daily_budget ||= @current_user.daily_budget(@date) - @current_user.variations.from_today(@date).map { |v| v.daily_value(@date) }.sum
  end

  def effective_daily_budget
    if current_daily_budget > 0
      current_daily_budget
    elsif saved_this_month < 0
      0
    else
      0
    end
  end

  def format_value(value)
    money = Money.new(value * 100, @current_user.currency)
    money.format(format: money.currency.to_s === "EUR" ? "%n %u" : "%u%n")
  end

  def format_budget_value(value, budget)
    if value < 0
      format_value(value.abs) + " overspent over #{format_value(budget)}"
    else
      format_value(value) + " remaining over #{format_value(budget)}"
    end
  end

  def saved_this_month
    @saved_this_month ||=
      if @date.day == 1
        0
      else
        (1..(@date.day - 1)).map do |day|
          @current_user.daily_budget(@date - day.days) - @current_user.variations.from_today(@date - day.days).map { |v| v.daily_value(@date - day.days) }.sum
        end.sum
      end
  end

  def overspent_daily_budget
    (current_daily_budget < 0 ? current_daily_budget.abs : 0)
  end

  def variations_for(recurring, range)
    if !recurring && range == 'this-month'
       @variations.where(recurring: false, base: true) + @variations.where(recurring: false, base: false).group_by(&:label).map do |label, variations|
        Variation.new(label: label, value: variations.map(&:value).sum)
      end
    else
      @variations.where(recurring: recurring)
    end
  end

  def spread_options_for(variation)
    if variation.recurring?
      {
        1 => "Until I remove it",
        2 => "Two months",
        3 => "Three months",
        4 => "Four months",
        5 => "Five months",
        6 => "Six months",
      }
    else
      options = { 1 => "No, only today" }

      date = (variation.created_at || Time.zone.now).to_datetime
      days_before_end_of_the_month = (date.end_of_month - date).to_i + 1
      if days_before_end_of_the_month > 7 # enough room for a week
        options[7] = "For 7 days"
      end

      options[days_before_end_of_the_month] = "Until the end of the month"

      options
    end
  end
end

app/views/variations/edit.html.slim
  = form_for @variation do |f|
    = f.hidden_field :base, { value: f.object.base }
    = f.hidden_field :user_id, { value: f.object.user.id }
    = f.hidden_field :recurring, { value: f.object.recurring }

    .modal.is-active
      .modal-background
      .modal-card
        header.modal-card-head
          p.modal-card-title
            | Edit “<strong>#{f.object.label}</strong>”
        section.modal-card-body
          - if flash[:error].present?
            .notification.is-danger= flash[:error]
          .field
            label.label
              | Give it a short and meaningful name
            .control
              = f.text_field :label, placeholder: "Restaurant", class: 'input is-large is-info', required: true
              - if !f.object.recurring
                datalist id="label-list"
                  - @current_user.variations.where(recurring: false, base: false).pluck(:label).uniq.each do |label|
                    option value=label

          .field
            label.label
              - if f.object.recurring?
                | What amount is spent every month?
              - else
                | What amount did you spent?
            .control
              = f.number_field :value, placeholder: "20", class: 'input is-large  is-info', required: true, step: 0.01

          .field
            label.label
              - if f.object.recurring?
                | For how long?
              - else
                | Do you want to spread this spending on more than a day?
            .control
              .select.is-large.is-fullwidth
                = f.select :spread, spread_options_for(f.object).map { |duration, name| [name, duration] }

        footer.modal-card-foot
          .level.is-mobile
            .level-left
              .level-item
                - unless f.object.base
                  = link_to variation_path(f.object), method: :delete, data: { confirm: "Are you sure want to delete “#{f.object.label}”?"}, class: "button is-danger is-outlined" do
                    = "Delete"
            .level-right
              .level-item
                = link_to "Cancel", variations_range_path(range: (f.object.recurring || f.object.base) ? 'this-month' : 'today'), class: "button"
                button.button.is-info= "Save and continue"

app/views/variations/index.html.slim
- if @current_user.monthly_budget.blank?
  = form_for @current_user do |f|
    .modal.is-active
      .modal-background
      .modal-card
        header.modal-card-head
          p.modal-card-title Hello #{@current_user.name}! Welcome to <strong class="brand">Daily</strong>.
        section.modal-card-body
          .content.is-medium
            p
              | First we need to know <strong>your monthly maximum budget</strong>. This budget can already take your fixed costs like your rent, taxes and subscriptions into consideration or you can add them in <strong class="brand">Daily</strong> later.
          .field
            label.label
              | Monthly budget
            .control
              = f.number_field :monthly_budget, placeholder: "1200", class: 'input is-large is-info', required: true
          .field
            label.label
              | Currency
            .control
              .select.is-large.is-fullwidth
                = f.select :currency, Money::Currency.all.map { |c| ["#{c.name} (#{c.symbol})", c.iso_code] }

        footer.modal-card-foot
          .level.is-mobile
            .level-left
            .level-right
              .level-item
                button.button.is-info= "Save and continue"

- elsif @current_user.base_variation.blank?
  = form_for Variation.new(user: @current_user, base: true) do |f|
    .modal.is-active
      .modal-background
      .modal-card
        header.modal-card-head
          p.modal-card-title
            | Just one more thing!
        section.modal-card-body
          .content.is-medium
            - if flash[:error].present?
              .notification.is-danger= flash[:error]
            p We need to know <strong>how much you already spent this month</strong>. This way we can already show you how much you saved (or not) based on your monthly budget.
          .field
            .control
              = f.hidden_field :user_id, { value: f.object.user.id }
              = f.hidden_field :base, { value: f.object.base }
              = f.hidden_field :label, { value: 'Already spent this month' }
              = f.number_field :value, placeholder: "200", class: 'input is-large is-info', required: true, step: 0.01
        footer.modal-card-foot
          .level.is-mobile
            .level-left
            .level-right
              .level-item
                button.button.is-info= "Save and continue"

#variations-index
  .tabs.is-centered.is-medium
    ul
      = active_link_to "Today", variations_range_path(range: "today"), class_active: 'is-active', wrap_tag: :li
      = active_link_to @date.strftime("%B"), variations_range_path(range: "this-month"), class_active: 'is-active', wrap_tag: :li

  .container
    .tags.is-centered
      - if params[:range] == 'today'
        .tag class="is-large #{effective_daily_budget < 0 && 'is-danger'}"
          = format_budget_value(effective_daily_budget, @current_user.daily_budget(@date))
      - else
        .tag class="is-large #{current_monthly_budget < 0 && 'is-danger'}"
          = format_budget_value(current_monthly_budget, @current_user.monthly_budget)
    - [true, false].each do |recurring|
      .content
        h5= recurring ? 'Recurring payments' : 'Spendings'
        - if variations_for(recurring, params[:range]).any?
          - variations_for(recurring, params[:range]).sort_by(&:label).each do |variation|
            .level.variation-level.is-mobile
              .level-left
                .level-item
                  = variation.label
              .level-right
                .level-item
                  - if (params[:range] == 'this-month' && recurring) || (params[:range] == 'today' && !recurring) || variation.base?
                    a href=edit_variation_path(variation)
                      strong= format_value(params[:range] == 'this-month' ? variation.monthly_value : variation.daily_value(@date))
                      span.icon
                        i.fas.fa-edit
                  - else
                    strong= format_value(params[:range] == 'this-month' ? variation.monthly_value : variation.daily_value(@date))
          .level.variation-level.is-total.is-mobile
            .level-left
              .level-item
                = "Total"
            .level-right
              .level-item
                strong= format_value(@variations.where(recurring: recurring).map { |v| params[:range] == 'this-month' ? v.monthly_value : v.daily_value(@date) }.sum)
        - else
          em None

    .content.has-text-centered#add-button-container
      - if params[:range] == 'today'
        = link_to new_variation_url(recurring: false), class: 'button is-info is-medium' do
          | Add&nbsp;<strong>spending</strong>
          span.icon.is-mall
            i.fas.fa-receipt
      - elsif params[:range] == 'this-month'
        = link_to new_variation_url(recurring: true), class: 'button is-info is-medium' do
          | Add&nbsp;<strong>recurring payment</strong>
          span.icon.is-mall
            i.fas.fa-file-contract

app/views/variations/new.html.slim
  = form_for Variation.new(user: @current_user, base: false, recurring: params[:recurring] == 'true') do |f|
    = f.hidden_field :base, { value: f.object.base }
    = f.hidden_field :user_id, { value: f.object.user.id }
    = f.hidden_field :recurring, { value: f.object.recurring }

    .modal.is-active
      .modal-background
      .modal-card
        header.modal-card-head
          p.modal-card-title
            - if params[:recurring] == 'true'
              | New <strong>recurring payment</strong>
            - else
              | New <strong>spending</strong>
        section.modal-card-body
          - if flash[:error].present?
            .notification.is-danger= flash[:error]
          .field
            label.label
              | Give it a short and meaningful name
            .control
              = f.text_field :label, placeholder: "Restaurant", class: 'input is-large is-info', required: true, list: 'label-list'
              - if params[:recurring] == 'false'
                datalist id="label-list"
                  - @current_user.variations.where(recurring: false, base: false).pluck(:label).uniq.each do |label|
                    option value=label
          .field
            label.label
              - if params[:recurring] == 'false'
                | What amount did you spent?
              - else
                | What amount is spent every month?
            .control
              = f.number_field :value, placeholder: "20", class: 'input is-large  is-info', required: true, step: 0.01
          .field
            label.label
              - if f.object.recurring?
                | For how long?
              - else
                | Do you want to spread this spending on more than a day?
            .control
              .select.is-large.is-fullwidth
                = f.select :spread, spread_options_for(f.object).map { |duration, name| [name, duration] }
        footer.modal-card-foot
          .level.is-mobile
            .level-left
            .level-right
              .level-item
                = link_to "Cancel", variations_range_path(range: (f.object.recurring || f.object.base) ? 'this-month' : 'today'), class: "button"
                button.button.is-info= "Save and continue"