config/routes.rb
Rails.application.routes.draw do
	root to: "variations#index"

  get 'users', to: 'users#create', as: :create_user
  post 'logout', to: 'users#logout'

  resources :users, only: [:new, :update, :edit, :destroy]
  resources :variations, only: [:create, :new, :edit, :update, :destroy]

  get '/privacy-policy', to: "pages#privacy_policy", as: :privacy_policy
  get '/terms-and-conditions', to: "pages#terms_and_conditions", as: :terms_and_conditions

  get '/:range', to: "variations#index", as: :variations_range
end

app/models/user.rb
class User < ApplicationRecord
  has_many :variations, dependent: :destroy

  has_one :base_variation, -> (user) { user.variations.where(base: true) }, class_name: "Variation"

  def daily_budget(date)
    (monthly_budget.to_i - variations.from_this_month(date).find_by(base: true)&.value.to_i).to_i / date.end_of_month.day
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    if user = authenticate_with_google
      cookies.signed[:user_id] = { value: user.id, expires: 1.year.from_now }
      redirect_to root_url
    else
      redirect_to new_session_url, alert: 'authentication_failed'
    end
  end

  def logout
    cookies.signed[:user_id] = nil

    redirect_to root_url
  end

  def edit
    user = User.find params[:id]
    authorize user
  end

  def update
    user = User.find params[:id]
    user.assign_attributes params.require(:user).permit(:monthly_budget, :currency)
    authorize user

    if user.save
      redirect_to root_url
    else
      redirect_to root_url, flash: { error: "An unexpected error occured."}
    end
  end

  def destroy
    user = User.find params[:id]
    authorize user
    user.destroy

    redirect_to root_url
  end

  private

  def authenticate_with_google
    if id_token = flash[:google_sign_in_token]
      identity = GoogleSignIn::Identity.new(id_token)
      User.find_or_create_by(google_id: identity.user_id) do |user|
        user.name = identity.name
      end
    elsif error = flash[:google_sign_in_error]
      logger.error "Google authentication error: #{error}"
      nil
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.slim
  = form_for @current_user do |f|
    = f.hidden_field :id, { value: f.object.id }

    .modal.is-active
      .modal-background
      .modal-card
        header.modal-card-head
          p.modal-card-title
            | #{@current_user.name}'s <strong>settings</strong>
        section.modal-card-body
          - if flash[:error].present?
            .notification.is-danger= flash[:error]

          .field
            label.label
              | Monthly budget
            .control
              = f.number_field :monthly_budget, placeholder: "1200", class: 'input is-large is-info', required: true

          .field
            label.label
              | Currency
            .control
              .select.is-large.is-fullwidth
                = f.select :currency, Money::Currency.all.map { |c| ["#{c.name} (#{c.symbol})", c.iso_code] }
          .field
            label.label
              | Current timezone
            .control
              = text_field_tag :timezone, Time.zone, disabled: true, class: 'input is-large is-info'

        footer.modal-card-foot
          .level.is-mobile
            .level-left
              .dropdown.is-hoverable.is-up
                .dropdown-trigger
                  a.button aria-haspopup="true" aria-controls="account-menu"
                    span
                      | Account
                    span.icon.is-small
                      i.fas.fa-angle-down aria-hidden="true"
                .dropdown-menu id="account-menu" role="menu"
                  .dropdown-content
                    = link_to privacy_policy_path, class: "dropdown-item" do
                      | Privacy policy
                    = link_to terms_and_conditions_path, class: "dropdown-item" do
                      | Terms and conditions
                    .dropdown-divider
                    = link_to user_path(@current_user), class: "dropdown-item has-text-danger", method: :delete, data: { confirm: "Are you sure you want to delete your account?"} do
                      | Delete account
                    .dropdown-divider
                    = link_to logout_path, class: "dropdown-item", method: :post do
                      | Sign out
            .level-right
              .level-item
                = link_to "Cancel", root_url, class: "button"
                button.button.is-info= "Save and continue"

app/views/users/new.html.slim
#users-new
  .hero.is-dark.is-medium.is-bold
    .hero-body
      .container
        .level.is-mobile
          .level-left
            .level-item
              .content
                h1.title.brand
                  | DAILY
                #service-description
                  | Simple <strong>day-by-day</strong> budget management
          .level-right
            .content.has-text-white
              = google_sign_in_button '', proceed_to: create_user_url, id: "sign-in-button"
              #info-links
                = link_to privacy_policy_path, class: 'button is-small is-outlined is-inverted is-dark' do
                  | Privacy policy
                = link_to terms_and_conditions_path, class: 'button is-small is-outlined is-inverted is-dark' do
                  | Terms and conditions